<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SanBongSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('san_bongs')->delete();
        DB::table('san_bongs')->truncate();
        DB::table('san_bongs')->insert([
            [
                'id'            => 1,
                'ma_san'        => 'SB001',
                'ten_san'       => 'Sân Số 1A',
                'dien_tich'     => 500,
                'gia_dau_thau'  => 1500000,
                'phan_tram_coc' => 30,
                'trang_thai'    => 1,
                'id_khu_vuc'    => 1,
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'id'            => 2,
                'ma_san'        => 'SB002',
                'ten_san'       => 'Sân Số 2A',
                'dien_tich'     => 450,
                'gia_dau_thau'  => 1400000,
                'phan_tram_coc' => 30,
                'trang_thai'    => 1,
                'id_khu_vuc'    => 1,
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'id'            => 3,
                'ma_san'        => 'SB003',
                'ten_san'       => 'Sân Số 3A',
                'dien_tich'     => 400,
                'gia_dau_thau'  => 1300000,
                'phan_tram_coc' => 30,
                'trang_thai'    => 1,
                'id_khu_vuc'    => 1,
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'id'            => 4,
                'ma_san'        => 'SB004',
                'ten_san'       => 'Sân Số 4A',
                'dien_tich'     => 500,
                'gia_dau_thau'  => 1600000,
                'phan_tram_coc' => 30,
                'trang_thai'    => 1,
                'id_khu_vuc'    => 1,
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'id'            => 5,
                'ma_san'        => 'SB005',
                'ten_san'       => 'Sân Số 5A',
                'dien_tich'     => 550,
                'gia_dau_thau'  => 1700000,
                'phan_tram_coc' => 30,
                'trang_thai'    => 1,
                'id_khu_vuc'    => 1,
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'id'            => 6,
                'ma_san'        => 'SB006',
                'ten_san'       => 'Sân Số 6A',
                'dien_tich'     => 600,
                'gia_dau_thau'  => 1800000,
                'phan_tram_coc' => 30,
                'trang_thai'    => 1,
                'id_khu_vuc'    => 1,
                'created_at'    => now(),
                'updated_at'    => now(),
            ],

            // Loại Sân B - 5 sân
            [
                'id'            => 7,
                'ma_san'        => 'SB007',
                'ten_san'       => 'Sân Số 1B',
                'dien_tich'     => 500,
                'gia_dau_thau'  => 1500000,
                'phan_tram_coc' => 30,
                'trang_thai'    => 1,
                'id_khu_vuc'    => 2,
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'id'            => 8,
                'ma_san'        => 'SB008',
                'ten_san'       => 'Sân Số 2B',
                'dien_tich'     => 450,
                'gia_dau_thau'  => 1400000,
                'phan_tram_coc' => 30,
                'trang_thai'    => 1,
                'id_khu_vuc'    => 2,
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'id'            => 9,
                'ma_san'        => 'SB009',
                'ten_san'       => 'Sân Số 3B',
                'dien_tich'     => 400,
                'gia_dau_thau'  => 1300000,
                'phan_tram_coc' => 30,
                'trang_thai'    => 1,
                'id_khu_vuc'    => 2,
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'id'            => 10,
                'ma_san'        => 'SB010',
                'ten_san'       => 'Sân Số 4B',
                'dien_tich'     => 500,
                'gia_dau_thau'  => 1600000,
                'phan_tram_coc' => 30,
                'trang_thai'    => 1,
                'id_khu_vuc'    => 2,
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'id'            => 11,
                'ma_san'        => 'SB011',
                'ten_san'       => 'Sân Số 5B',
                'dien_tich'     => 550,
                'gia_dau_thau'  => 1700000,
                'phan_tram_coc' => 30,
                'trang_thai'    => 1,
                'id_khu_vuc'    => 2,
                'created_at'    => now(),
                'updated_at'    => now(),
            ],

            // Loại Sân C - 5 sân
            [
                'id'            => 12,
                'ma_san'        => 'SB012',
                'ten_san'       => 'Sân Số 1C',
                'dien_tich'     => 500,
                'gia_dau_thau'  => 1500000,
                'phan_tram_coc' => 30,
                'trang_thai'    => 1,
                'id_khu_vuc'    => 3,
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'id'            => 13,
                'ma_san'        => 'SB013',
                'ten_san'       => 'Sân Số 2C',
                'dien_tich'     => 450,
                'gia_dau_thau'  => 1400000,
                'phan_tram_coc' => 30,
                'trang_thai'    => 1,
                'id_khu_vuc'    => 3,
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'id'            => 14,
                'ma_san'        => 'SB014',
                'ten_san'       => 'Sân Số 3C',
                'dien_tich'     => 400,
                'gia_dau_thau'  => 1300000,
                'phan_tram_coc' => 30,
                'trang_thai'    => 1,
                'id_khu_vuc'    => 3,
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'id'            => 15,
                'ma_san'        => 'SB015',
                'ten_san'       => 'Sân Số 4C',
                'dien_tich'     => 500,
                'gia_dau_thau'  => 1600000,
                'phan_tram_coc' => 30,
                'trang_thai'    => 1,
                'id_khu_vuc'    => 3,
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'id'            => 16,
                'ma_san'        => 'SB016',
                'ten_san'       => 'Sân Số 5C',
                'dien_tich'     => 550,
                'gia_dau_thau'  => 1700000,
                'phan_tram_coc' => 30,
                'trang_thai'    => 1,
                'id_khu_vuc'    => 3,
                'created_at'    => now(),
                'updated_at'    => now(),
            ],

            // Loại Sân D - 6 sân
            [
                'id'            => 17,
                'ma_san'        => 'SB017',
                'ten_san'       => 'Sân Số 1D',
                'dien_tich'     => 500,
                'gia_dau_thau'  => 1500000,
                'phan_tram_coc' => 30,
                'trang_thai'    => 1,
                'id_khu_vuc'    => 4,
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'id'            => 18,
                'ma_san'        => 'SB018',
                'ten_san'       => 'Sân Số 2D',
                'dien_tich'     => 450,
                'gia_dau_thau'  => 1400000,
                'phan_tram_coc' => 30,
                'trang_thai'    => 1,
                'id_khu_vuc'    => 4,
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'id'            => 19,
                'ma_san'        => 'SB019',
                'ten_san'       => 'Sân Số 3D',
                'dien_tich'     => 400,
                'gia_dau_thau'  => 1300000,
                'phan_tram_coc' => 30,
                'trang_thai'    => 1,
                'id_khu_vuc'    => 4,
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'id'            => 20,
                'ma_san'        => 'SB020',
                'ten_san'       => 'Sân Số 4D',
                'dien_tich'     => 500,
                'gia_dau_thau'  => 1600000,
                'phan_tram_coc' => 30,
                'trang_thai'    => 1,
                'id_khu_vuc'    => 4,
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'id'            => 21,
                'ma_san'        => 'SB021',
                'ten_san'       => 'Sân Số 5D',
                'dien_tich'     => 550,
                'gia_dau_thau'  => 1700000,
                'phan_tram_coc' => 30,
                'trang_thai'    => 1,
                'id_khu_vuc'    => 4,
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'id'            => 22,
                'ma_san'        => 'SB022',
                'ten_san'       => 'Sân Số 6D',
                'dien_tich'     => 600,
                'gia_dau_thau'  => 1800000,
                'phan_tram_coc' => 30,
                'trang_thai'    => 1,
                'id_khu_vuc'    => 4,
                'created_at'    => now(),
                'updated_at'    => now(),
            ],

            // Loại Sân E - 5 sân
            [
                'id'            => 23,
                'ma_san'        => 'SB023',
                'ten_san'       => 'Sân Số 1E',
                'dien_tich'     => 500,
                'gia_dau_thau'  => 1500000,
                'phan_tram_coc' => 30,
                'trang_thai'    => 1,
                'id_khu_vuc'    => 5,
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'id'            => 24,
                'ma_san'        => 'SB024',
                'ten_san'       => 'Sân Số 2E',
                'dien_tich'     => 450,
                'gia_dau_thau'  => 1400000,
                'phan_tram_coc' => 30,
                'trang_thai'    => 1,
                'id_khu_vuc'    => 5,
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'id'            => 25,
                'ma_san'        => 'SB025',
                'ten_san'       => 'Sân Số 3E',
                'dien_tich'     => 400,
                'gia_dau_thau'  => 1300000,
                'phan_tram_coc' => 30,
                'trang_thai'    => 1,
                'id_khu_vuc'    => 5,
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'id'            => 26,
                'ma_san'        => 'SB026',
                'ten_san'       => 'Sân Số 4E',
                'dien_tich'     => 500,
                'gia_dau_thau'  => 1600000,
                'phan_tram_coc' => 30,
                'trang_thai'    => 1,
                'id_khu_vuc'    => 5,
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'id'            => 27,
                'ma_san'        => 'SB027',
                'ten_san'       => 'Sân Số 5E',
                'dien_tich'     => 550,
                'gia_dau_thau'  => 1700000,
                'phan_tram_coc' => 30,
                'trang_thai'    => 1,
                'id_khu_vuc'    => 5,
                'created_at'    => now(),
                'updated_at'    => now(),
            ]
        ]);
    }
}
